### PR TITLE
Sgt back end

### PR DESCRIPTION
**Pull request by easton-morris**
Adding Screenshots of all routes shortly.

### CODE REVIEW

**Comment by easton-morris** [comment]
image
Two examples of 500 failures when I had a bad SQL query referencing a non-existent row. The rest of the 500 catches are the same.

**Comment by easton-morris** [comment]
image
GET generic 200 Success

**Comment by easton-morris** [comment]
image
POST 201 Success
image
POST 400 Fail

**Comment by easton-morris** [comment]
image
DELETE 204 Success
image
DELETE 404 Fail
image
DELETE 400 Fail

**Comment by easton-morris** [comment]
image
PUT 200 Success
image
PUT 404 Fail
image
PUT 400 Fail

**Review by TimelikeClosure — APPROVED** [review]

**Pull request merged**
